/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt -i cl.ggo -F cl_cmdline -f cl_cmdline_parser -a cl_cmdline_args

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cl_cmdline.h"

const char *cl_cmdline_args_purpose = "";

const char *cl_cmdline_args_usage = "Usage: cl [OPTIONS] <cnk app> [ -- arguments for cnk app ]";

const char *cl_cmdline_args_description = "";

const char *cl_cmdline_args_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -p, --spc0=SPC number         SPC number (multiple of 4)  (default=`0')",
  "  -n, --num_procs=number        Number processes (p + n*t <= 64) (default: 1)  \n                                  (default=`1')",
  "  -t, --num_threads=number      Number of threads per process (default: 1)  \n                                  (default=`1')",
  "  -m, --num_memchunks=number    Number of memory chunks to use (<= n*t, \n                                  default: n*t)",
  "  -s, --shm[=MB]                Enable shared memory and optionally specify \n                                  size  (default=`-1')",
  "  -d, --debug                   Enable debugging  (default=off)",
  "  -b, --dbg_buffer              Enable debugging with internal buffer (implies \n                                  -d)  (default=off)",
  "  -a, --action_tracker          Enable action tracker  (default=off)",
  "  -P, --alloc_policy=ENUM       SPC allocation policy  (possible \n                                  values=\"CORES\", \"LINEAR\", \"TWO_THREADS\" \n                                  default=`CORES')",
  "      --job_mapOrder=string     Mapping order of torus dimensions to job ranks  \n                                  (default=`ABCDET')",
  "      --job_ranks=INT           Number of active ranks in the job (defaults to \n                                  use the whole block)",
  "      --job_corner=<A,B,C,D,E>  Coordinates of the job's corner",
  "      --job_shape=<A,B,C,D,E>   Shape of the job, in the five dimensions",
  "      --serial_procs            Run processes serially  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_ENUM
} cl_cmdline_parser_arg_type;

static
void clear_given (struct cl_cmdline_args *args_info);
static
void clear_args (struct cl_cmdline_args *args_info);

static int
cl_cmdline_parser_internal (int argc, char **argv, struct cl_cmdline_args *args_info,
                        struct cl_cmdline_parser_params *params, const char *additional_error);

static int
cl_cmdline_parser_required2 (struct cl_cmdline_args *args_info, const char *prog_name, const char *additional_error);

const char *cl_cmdline_parser_alloc_policy_values[] = {"CORES", "LINEAR", "TWO_THREADS", 0}; /*< Possible values for alloc_policy. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct cl_cmdline_args *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->spc0_given = 0 ;
  args_info->num_procs_given = 0 ;
  args_info->num_threads_given = 0 ;
  args_info->num_memchunks_given = 0 ;
  args_info->shm_given = 0 ;
  args_info->debug_given = 0 ;
  args_info->dbg_buffer_given = 0 ;
  args_info->action_tracker_given = 0 ;
  args_info->alloc_policy_given = 0 ;
  args_info->job_mapOrder_given = 0 ;
  args_info->job_ranks_given = 0 ;
  args_info->job_corner_given = 0 ;
  args_info->job_shape_given = 0 ;
  args_info->serial_procs_given = 0 ;
}

static
void clear_args (struct cl_cmdline_args *args_info)
{
  FIX_UNUSED (args_info);
  args_info->spc0_arg = 0;
  args_info->spc0_orig = NULL;
  args_info->num_procs_arg = 1;
  args_info->num_procs_orig = NULL;
  args_info->num_threads_arg = 1;
  args_info->num_threads_orig = NULL;
  args_info->num_memchunks_orig = NULL;
  args_info->shm_arg = -1;
  args_info->shm_orig = NULL;
  args_info->debug_flag = 0;
  args_info->dbg_buffer_flag = 0;
  args_info->action_tracker_flag = 0;
  args_info->alloc_policy_arg = alloc_policy_arg_CORES;
  args_info->alloc_policy_orig = NULL;
  args_info->job_mapOrder_arg = gengetopt_strdup ("ABCDET");
  args_info->job_mapOrder_orig = NULL;
  args_info->job_ranks_orig = NULL;
  args_info->job_corner_arg = NULL;
  args_info->job_corner_orig = NULL;
  args_info->job_shape_arg = NULL;
  args_info->job_shape_orig = NULL;
  args_info->serial_procs_flag = 0;
  
}

static
void init_args_info(struct cl_cmdline_args *args_info)
{


  args_info->help_help = cl_cmdline_args_help[0] ;
  args_info->version_help = cl_cmdline_args_help[1] ;
  args_info->spc0_help = cl_cmdline_args_help[2] ;
  args_info->num_procs_help = cl_cmdline_args_help[3] ;
  args_info->num_threads_help = cl_cmdline_args_help[4] ;
  args_info->num_memchunks_help = cl_cmdline_args_help[5] ;
  args_info->shm_help = cl_cmdline_args_help[6] ;
  args_info->debug_help = cl_cmdline_args_help[7] ;
  args_info->dbg_buffer_help = cl_cmdline_args_help[8] ;
  args_info->action_tracker_help = cl_cmdline_args_help[9] ;
  args_info->alloc_policy_help = cl_cmdline_args_help[10] ;
  args_info->job_mapOrder_help = cl_cmdline_args_help[11] ;
  args_info->job_ranks_help = cl_cmdline_args_help[12] ;
  args_info->job_corner_help = cl_cmdline_args_help[13] ;
  args_info->job_shape_help = cl_cmdline_args_help[14] ;
  args_info->serial_procs_help = cl_cmdline_args_help[15] ;
  
}

void
cl_cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CL_CMDLINE_PARSER_PACKAGE_NAME) ? CL_CMDLINE_PARSER_PACKAGE_NAME : CL_CMDLINE_PARSER_PACKAGE),
     CL_CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cl_cmdline_parser_print_version ();

  if (strlen(cl_cmdline_args_purpose) > 0)
    printf("\n%s\n", cl_cmdline_args_purpose);

  if (strlen(cl_cmdline_args_usage) > 0)
    printf("\n%s\n", cl_cmdline_args_usage);

  printf("\n");

  if (strlen(cl_cmdline_args_description) > 0)
    printf("%s\n\n", cl_cmdline_args_description);
}

void
cl_cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (cl_cmdline_args_help[i])
    printf("%s\n", cl_cmdline_args_help[i++]);
}

void
cl_cmdline_parser_init (struct cl_cmdline_args *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cl_cmdline_parser_params_init(struct cl_cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cl_cmdline_parser_params *
cl_cmdline_parser_params_create(void)
{
  struct cl_cmdline_parser_params *params = 
    (struct cl_cmdline_parser_params *)malloc(sizeof(struct cl_cmdline_parser_params));
  cl_cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cl_cmdline_parser_release (struct cl_cmdline_args *args_info)
{

  free_string_field (&(args_info->spc0_orig));
  free_string_field (&(args_info->num_procs_orig));
  free_string_field (&(args_info->num_threads_orig));
  free_string_field (&(args_info->num_memchunks_orig));
  free_string_field (&(args_info->shm_orig));
  free_string_field (&(args_info->alloc_policy_orig));
  free_string_field (&(args_info->job_mapOrder_arg));
  free_string_field (&(args_info->job_mapOrder_orig));
  free_string_field (&(args_info->job_ranks_orig));
  free_string_field (&(args_info->job_corner_arg));
  free_string_field (&(args_info->job_corner_orig));
  free_string_field (&(args_info->job_shape_arg));
  free_string_field (&(args_info->job_shape_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cl_cmdline_parser_dump(FILE *outfile, struct cl_cmdline_args *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CL_CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->spc0_given)
    write_into_file(outfile, "spc0", args_info->spc0_orig, 0);
  if (args_info->num_procs_given)
    write_into_file(outfile, "num_procs", args_info->num_procs_orig, 0);
  if (args_info->num_threads_given)
    write_into_file(outfile, "num_threads", args_info->num_threads_orig, 0);
  if (args_info->num_memchunks_given)
    write_into_file(outfile, "num_memchunks", args_info->num_memchunks_orig, 0);
  if (args_info->shm_given)
    write_into_file(outfile, "shm", args_info->shm_orig, 0);
  if (args_info->debug_given)
    write_into_file(outfile, "debug", 0, 0 );
  if (args_info->dbg_buffer_given)
    write_into_file(outfile, "dbg_buffer", 0, 0 );
  if (args_info->action_tracker_given)
    write_into_file(outfile, "action_tracker", 0, 0 );
  if (args_info->alloc_policy_given)
    write_into_file(outfile, "alloc_policy", args_info->alloc_policy_orig, cl_cmdline_parser_alloc_policy_values);
  if (args_info->job_mapOrder_given)
    write_into_file(outfile, "job_mapOrder", args_info->job_mapOrder_orig, 0);
  if (args_info->job_ranks_given)
    write_into_file(outfile, "job_ranks", args_info->job_ranks_orig, 0);
  if (args_info->job_corner_given)
    write_into_file(outfile, "job_corner", args_info->job_corner_orig, 0);
  if (args_info->job_shape_given)
    write_into_file(outfile, "job_shape", args_info->job_shape_orig, 0);
  if (args_info->serial_procs_given)
    write_into_file(outfile, "serial_procs", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cl_cmdline_parser_file_save(const char *filename, struct cl_cmdline_args *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CL_CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cl_cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cl_cmdline_parser_free (struct cl_cmdline_args *args_info)
{
  cl_cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cl_cmdline_parser (int argc, char **argv, struct cl_cmdline_args *args_info)
{
  return cl_cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cl_cmdline_parser_ext (int argc, char **argv, struct cl_cmdline_args *args_info,
                   struct cl_cmdline_parser_params *params)
{
  int result;
  result = cl_cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cl_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cl_cmdline_parser2 (int argc, char **argv, struct cl_cmdline_args *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cl_cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cl_cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cl_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cl_cmdline_parser_required (struct cl_cmdline_args *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cl_cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cl_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cl_cmdline_parser_required2 (struct cl_cmdline_args *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  
  /* checks for dependences among options */
  if (args_info->job_corner_given && ! args_info->job_shape_given)
    {
      fprintf (stderr, "%s: '--job_corner' option depends on option 'job_shape'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (args_info->job_shape_given && ! args_info->job_corner_given)
    {
      fprintf (stderr, "%s: '--job_shape' option depends on option 'job_corner'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cl_cmdline_parser_params.check_ambiguity
 * @param override @see cl_cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cl_cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cl_cmdline_parser_internal (
  int argc, char **argv, struct cl_cmdline_args *args_info,
                        struct cl_cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct cl_cmdline_args local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cl_cmdline_parser_init (args_info);

  cl_cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "spc0",	1, NULL, 'p' },
        { "num_procs",	1, NULL, 'n' },
        { "num_threads",	1, NULL, 't' },
        { "num_memchunks",	1, NULL, 'm' },
        { "shm",	2, NULL, 's' },
        { "debug",	0, NULL, 'd' },
        { "dbg_buffer",	0, NULL, 'b' },
        { "action_tracker",	0, NULL, 'a' },
        { "alloc_policy",	1, NULL, 'P' },
        { "job_mapOrder",	1, NULL, 0 },
        { "job_ranks",	1, NULL, 0 },
        { "job_corner",	1, NULL, 0 },
        { "job_shape",	1, NULL, 0 },
        { "serial_procs",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVp:n:t:m:s::dbaP:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cl_cmdline_parser_print_help ();
          cl_cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cl_cmdline_parser_print_version ();
          cl_cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'p':	/* SPC number (multiple of 4).  */
        
        
          if (update_arg( (void *)&(args_info->spc0_arg), 
               &(args_info->spc0_orig), &(args_info->spc0_given),
              &(local_args_info.spc0_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "spc0", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Number processes (p + n*t <= 64) (default: 1).  */
        
        
          if (update_arg( (void *)&(args_info->num_procs_arg), 
               &(args_info->num_procs_orig), &(args_info->num_procs_given),
              &(local_args_info.num_procs_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "num_procs", 'n',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Number of threads per process (default: 1).  */
        
        
          if (update_arg( (void *)&(args_info->num_threads_arg), 
               &(args_info->num_threads_orig), &(args_info->num_threads_given),
              &(local_args_info.num_threads_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "num_threads", 't',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Number of memory chunks to use (<= n*t, default: n*t).  */
        
        
          if (update_arg( (void *)&(args_info->num_memchunks_arg), 
               &(args_info->num_memchunks_orig), &(args_info->num_memchunks_given),
              &(local_args_info.num_memchunks_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "num_memchunks", 'm',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Enable shared memory and optionally specify size.  */
        
        
          if (update_arg( (void *)&(args_info->shm_arg), 
               &(args_info->shm_orig), &(args_info->shm_given),
              &(local_args_info.shm_given), optarg, 0, "-1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "shm", 's',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Enable debugging.  */
        
        
          if (update_arg((void *)&(args_info->debug_flag), 0, &(args_info->debug_given),
              &(local_args_info.debug_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "debug", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Enable debugging with internal buffer (implies -d).  */
        
        
          if (update_arg((void *)&(args_info->dbg_buffer_flag), 0, &(args_info->dbg_buffer_given),
              &(local_args_info.dbg_buffer_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "dbg_buffer", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Enable action tracker.  */
        
        
          if (update_arg((void *)&(args_info->action_tracker_flag), 0, &(args_info->action_tracker_given),
              &(local_args_info.action_tracker_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "action_tracker", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* SPC allocation policy.  */
        
        
          if (update_arg( (void *)&(args_info->alloc_policy_arg), 
               &(args_info->alloc_policy_orig), &(args_info->alloc_policy_given),
              &(local_args_info.alloc_policy_given), optarg, cl_cmdline_parser_alloc_policy_values, "CORES", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "alloc_policy", 'P',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Mapping order of torus dimensions to job ranks.  */
          if (strcmp (long_options[option_index].name, "job_mapOrder") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->job_mapOrder_arg), 
                 &(args_info->job_mapOrder_orig), &(args_info->job_mapOrder_given),
                &(local_args_info.job_mapOrder_given), optarg, 0, "ABCDET", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "job_mapOrder", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of active ranks in the job (defaults to use the whole block).  */
          else if (strcmp (long_options[option_index].name, "job_ranks") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->job_ranks_arg), 
                 &(args_info->job_ranks_orig), &(args_info->job_ranks_given),
                &(local_args_info.job_ranks_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "job_ranks", '-',
                additional_error))
              goto failure;
          
          }
          /* Coordinates of the job's corner.  */
          else if (strcmp (long_options[option_index].name, "job_corner") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->job_corner_arg), 
                 &(args_info->job_corner_orig), &(args_info->job_corner_given),
                &(local_args_info.job_corner_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "job_corner", '-',
                additional_error))
              goto failure;
          
          }
          /* Shape of the job, in the five dimensions.  */
          else if (strcmp (long_options[option_index].name, "job_shape") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->job_shape_arg), 
                 &(args_info->job_shape_orig), &(args_info->job_shape_given),
                &(local_args_info.job_shape_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "job_shape", '-',
                additional_error))
              goto failure;
          
          }
          /* Run processes serially.  */
          else if (strcmp (long_options[option_index].name, "serial_procs") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->serial_procs_flag), 0, &(args_info->serial_procs_given),
                &(local_args_info.serial_procs_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "serial_procs", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CL_CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += cl_cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cl_cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cl_cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
