/** @file sfjs_cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.5
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef SFJS_CMDLINE_H
#define SFJS_CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef SFJS_CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define SFJS_CMDLINE_PARSER_PACKAGE "sfjs"
#endif

#ifndef SFJS_CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define SFJS_CMDLINE_PARSER_PACKAGE_NAME "sfjs"
#endif

#ifndef SFJS_CMDLINE_PARSER_VERSION
/** @brief the program version */
#define SFJS_CMDLINE_PARSER_VERSION "0.00001"
#endif

enum enum_subblock { subblock__NULL = -1, subblock_arg_prep = 0, subblock_arg_gion, subblock_arg_go };

/** @brief Where the command line options are stored */
struct sfjs_cmdline_args
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  int nodes_arg;	/**< @brief Number of nodes used for the job (derived from SLURM variables if not specified).  */
  char * nodes_orig;	/**< @brief Number of nodes used for the job (derived from SLURM variables if not specified) original value given at command line.  */
  const char *nodes_help; /**< @brief Number of nodes used for the job (derived from SLURM variables if not specified) help description.  */
  int procs_arg;	/**< @brief Number of processes per node (default='1').  */
  char * procs_orig;	/**< @brief Number of processes per node original value given at command line.  */
  const char *procs_help; /**< @brief Number of processes per node help description.  */
  enum enum_subblock subblock_arg;	/**< @brief subblock handling.  */
  char * subblock_orig;	/**< @brief subblock handling original value given at command line.  */
  const char *subblock_help; /**< @brief subblock handling help description.  */
  int reset_block_barrier_flag;	/**< @brief reset block barrier to initial state (default=off).  */
  const char *reset_block_barrier_help; /**< @brief reset block barrier to initial state help description.  */
  int debug_flag;	/**< @brief Enable debugging (default=off).  */
  const char *debug_help; /**< @brief Enable debugging help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int nodes_given ;	/**< @brief Whether nodes was given.  */
  unsigned int procs_given ;	/**< @brief Whether procs was given.  */
  unsigned int subblock_given ;	/**< @brief Whether subblock was given.  */
  unsigned int reset_block_barrier_given ;	/**< @brief Whether reset-block-barrier was given.  */
  unsigned int debug_given ;	/**< @brief Whether debug was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct sfjs_cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure sfjs_cmdline_args (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure sfjs_cmdline_args (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *sfjs_cmdline_args_purpose;
/** @brief the usage string of the program */
extern const char *sfjs_cmdline_args_usage;
/** @brief all the lines making the help output */
extern const char *sfjs_cmdline_args_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int sfjs_cmdline_parser (int argc, char **argv,
  struct sfjs_cmdline_args *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use sfjs_cmdline_parser_ext() instead
 */
int sfjs_cmdline_parser2 (int argc, char **argv,
  struct sfjs_cmdline_args *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int sfjs_cmdline_parser_ext (int argc, char **argv,
  struct sfjs_cmdline_args *args_info,
  struct sfjs_cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int sfjs_cmdline_parser_dump(FILE *outfile,
  struct sfjs_cmdline_args *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int sfjs_cmdline_parser_file_save(const char *filename,
  struct sfjs_cmdline_args *args_info);

/**
 * Print the help
 */
void sfjs_cmdline_parser_print_help(void);
/**
 * Print the version
 */
void sfjs_cmdline_parser_print_version(void);

/**
 * Initializes all the fields a sfjs_cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void sfjs_cmdline_parser_params_init(struct sfjs_cmdline_parser_params *params);

/**
 * Allocates dynamically a sfjs_cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized sfjs_cmdline_parser_params structure
 */
struct sfjs_cmdline_parser_params *sfjs_cmdline_parser_params_create(void);

/**
 * Initializes the passed sfjs_cmdline_args structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void sfjs_cmdline_parser_init (struct sfjs_cmdline_args *args_info);
/**
 * Deallocates the string fields of the sfjs_cmdline_args structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void sfjs_cmdline_parser_free (struct sfjs_cmdline_args *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int sfjs_cmdline_parser_required (struct sfjs_cmdline_args *args_info,
  const char *prog_name);

extern const char *sfjs_cmdline_parser_subblock_values[];  /**< @brief Possible values for subblock. */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* SFJS_CMDLINE_H */
