/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt -i sfjs.ggo -F sfjs_cmdline -f sfjs_cmdline_parser -a sfjs_cmdline_args

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "sfjs_cmdline.h"

const char *sfjs_cmdline_args_purpose = "";

const char *sfjs_cmdline_args_usage = "Usage: sfjs [OPTIONS] -- [OPTIONS for cl] -- <cnk app> [ -- arguments for cnk app ]";

const char *sfjs_cmdline_args_description = "FusedOS Job System, a cl frontend for CNK MPI apps";

const char *sfjs_cmdline_args_help[] = {
  "  -h, --help                 Print help and exit",
  "  -V, --version              Print version and exit",
  "  -n, --nodes=nr             Number of nodes used for the job (derived from \n                               SLURM variables if not specified)",
  "  -p, --procs=nr             Number of processes per node  (default=`1')",
  "  -s, --subblock=ENUM        subblock handling  (possible values=\"prep\", \n                               \"gion\", \"go\")",
  "      --reset-block-barrier  reset block barrier to initial state  \n                               (default=off)",
  "  -d, --debug                Enable debugging  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_INT
  , ARG_ENUM
} sfjs_cmdline_parser_arg_type;

static
void clear_given (struct sfjs_cmdline_args *args_info);
static
void clear_args (struct sfjs_cmdline_args *args_info);

static int
sfjs_cmdline_parser_internal (int argc, char **argv, struct sfjs_cmdline_args *args_info,
                        struct sfjs_cmdline_parser_params *params, const char *additional_error);


const char *sfjs_cmdline_parser_subblock_values[] = {"prep", "gion", "go", 0}; /*< Possible values for subblock. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct sfjs_cmdline_args *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->nodes_given = 0 ;
  args_info->procs_given = 0 ;
  args_info->subblock_given = 0 ;
  args_info->reset_block_barrier_given = 0 ;
  args_info->debug_given = 0 ;
}

static
void clear_args (struct sfjs_cmdline_args *args_info)
{
  FIX_UNUSED (args_info);
  args_info->nodes_orig = NULL;
  args_info->procs_arg = 1;
  args_info->procs_orig = NULL;
  args_info->subblock_arg = subblock__NULL;
  args_info->subblock_orig = NULL;
  args_info->reset_block_barrier_flag = 0;
  args_info->debug_flag = 0;
  
}

static
void init_args_info(struct sfjs_cmdline_args *args_info)
{


  args_info->help_help = sfjs_cmdline_args_help[0] ;
  args_info->version_help = sfjs_cmdline_args_help[1] ;
  args_info->nodes_help = sfjs_cmdline_args_help[2] ;
  args_info->procs_help = sfjs_cmdline_args_help[3] ;
  args_info->subblock_help = sfjs_cmdline_args_help[4] ;
  args_info->reset_block_barrier_help = sfjs_cmdline_args_help[5] ;
  args_info->debug_help = sfjs_cmdline_args_help[6] ;
  
}

void
sfjs_cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(SFJS_CMDLINE_PARSER_PACKAGE_NAME) ? SFJS_CMDLINE_PARSER_PACKAGE_NAME : SFJS_CMDLINE_PARSER_PACKAGE),
     SFJS_CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  sfjs_cmdline_parser_print_version ();

  if (strlen(sfjs_cmdline_args_purpose) > 0)
    printf("\n%s\n", sfjs_cmdline_args_purpose);

  if (strlen(sfjs_cmdline_args_usage) > 0)
    printf("\n%s\n", sfjs_cmdline_args_usage);

  printf("\n");

  if (strlen(sfjs_cmdline_args_description) > 0)
    printf("%s\n\n", sfjs_cmdline_args_description);
}

void
sfjs_cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (sfjs_cmdline_args_help[i])
    printf("%s\n", sfjs_cmdline_args_help[i++]);
}

void
sfjs_cmdline_parser_init (struct sfjs_cmdline_args *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
sfjs_cmdline_parser_params_init(struct sfjs_cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct sfjs_cmdline_parser_params *
sfjs_cmdline_parser_params_create(void)
{
  struct sfjs_cmdline_parser_params *params = 
    (struct sfjs_cmdline_parser_params *)malloc(sizeof(struct sfjs_cmdline_parser_params));
  sfjs_cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
sfjs_cmdline_parser_release (struct sfjs_cmdline_args *args_info)
{

  free_string_field (&(args_info->nodes_orig));
  free_string_field (&(args_info->procs_orig));
  free_string_field (&(args_info->subblock_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
sfjs_cmdline_parser_dump(FILE *outfile, struct sfjs_cmdline_args *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", SFJS_CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->nodes_given)
    write_into_file(outfile, "nodes", args_info->nodes_orig, 0);
  if (args_info->procs_given)
    write_into_file(outfile, "procs", args_info->procs_orig, 0);
  if (args_info->subblock_given)
    write_into_file(outfile, "subblock", args_info->subblock_orig, sfjs_cmdline_parser_subblock_values);
  if (args_info->reset_block_barrier_given)
    write_into_file(outfile, "reset-block-barrier", 0, 0 );
  if (args_info->debug_given)
    write_into_file(outfile, "debug", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
sfjs_cmdline_parser_file_save(const char *filename, struct sfjs_cmdline_args *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", SFJS_CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = sfjs_cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
sfjs_cmdline_parser_free (struct sfjs_cmdline_args *args_info)
{
  sfjs_cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
sfjs_cmdline_parser (int argc, char **argv, struct sfjs_cmdline_args *args_info)
{
  return sfjs_cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
sfjs_cmdline_parser_ext (int argc, char **argv, struct sfjs_cmdline_args *args_info,
                   struct sfjs_cmdline_parser_params *params)
{
  int result;
  result = sfjs_cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      sfjs_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
sfjs_cmdline_parser2 (int argc, char **argv, struct sfjs_cmdline_args *args_info, int override, int initialize, int check_required)
{
  int result;
  struct sfjs_cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = sfjs_cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      sfjs_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
sfjs_cmdline_parser_required (struct sfjs_cmdline_args *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see sfjs_cmdline_parser_params.check_ambiguity
 * @param override @see sfjs_cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               sfjs_cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
sfjs_cmdline_parser_internal (
  int argc, char **argv, struct sfjs_cmdline_args *args_info,
                        struct sfjs_cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct sfjs_cmdline_args local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    sfjs_cmdline_parser_init (args_info);

  sfjs_cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "nodes",	1, NULL, 'n' },
        { "procs",	1, NULL, 'p' },
        { "subblock",	1, NULL, 's' },
        { "reset-block-barrier",	0, NULL, 0 },
        { "debug",	0, NULL, 'd' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVn:p:s:d", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          sfjs_cmdline_parser_print_help ();
          sfjs_cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          sfjs_cmdline_parser_print_version ();
          sfjs_cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'n':	/* Number of nodes used for the job (derived from SLURM variables if not specified).  */
        
        
          if (update_arg( (void *)&(args_info->nodes_arg), 
               &(args_info->nodes_orig), &(args_info->nodes_given),
              &(local_args_info.nodes_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "nodes", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Number of processes per node.  */
        
        
          if (update_arg( (void *)&(args_info->procs_arg), 
               &(args_info->procs_orig), &(args_info->procs_given),
              &(local_args_info.procs_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "procs", 'p',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* subblock handling.  */
        
        
          if (update_arg( (void *)&(args_info->subblock_arg), 
               &(args_info->subblock_orig), &(args_info->subblock_given),
              &(local_args_info.subblock_given), optarg, sfjs_cmdline_parser_subblock_values, 0, ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "subblock", 's',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Enable debugging.  */
        
        
          if (update_arg((void *)&(args_info->debug_flag), 0, &(args_info->debug_given),
              &(local_args_info.debug_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "debug", 'd',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* reset block barrier to initial state.  */
          if (strcmp (long_options[option_index].name, "reset-block-barrier") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->reset_block_barrier_flag), 0, &(args_info->reset_block_barrier_given),
                &(local_args_info.reset_block_barrier_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "reset-block-barrier", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", SFJS_CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  sfjs_cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  sfjs_cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
