/* begin_generated_IBM_copyright_prolog                             */
/*                                                                  */
/* This is an automatically generated copyright prolog.             */
/* After initializing,  DO NOT MODIFY OR MOVE                       */
/*  --------------------------------------------------------------- */
/*                                                                  */
/* Licensed Materials - Property of IBM                             */
/* Blue Gene/Q                                                      */
/* (C) Copyright IBM Corp.  2010, 2012                              */
/* US Government Users Restricted Rights - Use, duplication or      */
/*   disclosure restricted by GSA ADP Schedule Contract with IBM    */
/*   Corp.                                                          */
/*                                                                  */
/* This software is available to you under the Eclipse Public       */
/* License (EPL).                                                   */
/*                                                                  */
/*  --------------------------------------------------------------- */
/*                                                                  */
/* end_generated_IBM_copyright_prolog                               */
#ifndef _BQC_FW_VIRTUALMAP_H_ // Prevent multiple inclusion
#define _BQC_FW_VIRTUALMAP_H_

#include <hwi/include/bqc/PhysicalMap.h>

#define VA_MINADDR_MAINMEMORYACCESS PHYMAP_MINADDR_MAINMEMORYACCESS
#define VA_MAXADDR_MAINMEMORYACCESS PHYMAP_MAXADDR_MAINMEMORYACCESS
#define VA_SIZE_MAINMEMORYACCESS    (VA_MAXADDR_MAINMEMORYACCESS - VA_MINADDR_MAINMEMORYACCESS+1)
#define VA_MASK_MAINMEMORYACCESS    (VA_MAXADDR_MAINMEMORYACCESS ^ VA_MINADDR_MAINMEMORYACCESS)

#define VA_MINADDR_MAINMEMORY PHYMAP_MINADDR_MAINMEMORY
#define VA_MAXADDR_MAINMEMORY PHYMAP_MAXADDR_MAINMEMORY
#define VA_SIZE_MAINMEMORY    (VA_MAXADDR_MAINMEMORY - VA_MINADDR_MAINMEMORY+1)
#define VA_MASK_MAINMEMORY    (VA_MAXADDR_MAINMEMORY ^ VA_MINADDR_MAINMEMORY)

#define VA_MINADDR_TLS1 PHYMAP_MINADDR_TLS1
#define VA_MAXADDR_TLS1 PHYMAP_MAXADDR_TLS1
#define VA_SIZE_TLS1    (VA_MAXADDR_TLS1 - VA_MINADDR_TLS1+1)
#define VA_MASK_TLS1    (VA_MAXADDR_TLS1 ^ VA_MINADDR_TLS1)

#define VA_MINADDR_TLS2 PHYMAP_MINADDR_TLS2
#define VA_MAXADDR_TLS2 PHYMAP_MAXADDR_TLS2
#define VA_SIZE_TLS2    (VA_MAXADDR_TLS2 - VA_MINADDR_TLS2+1)
#define VA_MASK_TLS2    (VA_MAXADDR_TLS2 ^ VA_MINADDR_TLS2)

#define VA_MINADDR_TLS3 PHYMAP_MINADDR_TLS3
#define VA_MAXADDR_TLS3 PHYMAP_MAXADDR_TLS3
#define VA_SIZE_TLS3    (VA_MAXADDR_TLS3 - VA_MINADDR_TLS3+1)
#define VA_MASK_TLS3    (VA_MAXADDR_TLS3 ^ VA_MINADDR_TLS3)

#define VA_MINADDR_ATOMICOPS PHYMAP_MINADDR_ATOMICOPS
#define VA_MAXADDR_ATOMICOPS PHYMAP_MAXADDR_ATOMICOPS
#define VA_SIZE_ATOMICOPS    (VA_MAXADDR_ATOMICOPS - VA_MINADDR_ATOMICOPS+1)
#define VA_MASK_ATOMICOPS    (VA_MAXADDR_ATOMICOPS ^ VA_MINADDR_ATOMICOPS)

#define VA_MINADDR_CATOMICOPS PHYMAP_MINADDR_CATOMICOPS
#define VA_MAXADDR_CATOMICOPS PHYMAP_MAXADDR_CATOMICOPS
#define VA_SIZE_CATOMICOPS    (VA_MAXADDR_CATOMICOPS - VA_MINADDR_CATOMICOPS+1)
#define VA_MASK_CATOMICOPS    (VA_MAXADDR_CATOMICOPS ^ VA_MINADDR_CATOMICOPS)

#define VA_MINADDR_PCIE PHYMAP_MINADDR_PCIE
#define VA_MAXADDR_PCIE PHYMAP_MAXADDR_PCIE
#define VA_SIZE_PCIE    (VA_MAXADDR_PCIE - VA_MINADDR_PCIE+1)
#define VA_MASK_PCIE    (VA_MAXADDR_PCIE ^ VA_MINADDR_PCIE)

#define VA_MINADDR_MMIO PHYMAP_MINADDR_MMIO
#define VA_MAXADDR_MMIO PHYMAP_MAXADDR_MMIO
#define VA_SIZE_MMIO   (VA_MAXADDR_MMIO - VA_MINADDR_MMIO+1)
#define VA_MASK_MMIO    (VA_MAXADDR_MMIO ^ VA_MINADDR_MMIO)

#define VA_MINADDR_DCR PHYMAP_MINADDR_DCR
#define VA_MAXADDR_DCR PHYMAP_MAXADDR_DCR
#define VA_SIZE_DCR    (VA_MAXADDR_DCR - VA_MINADDR_DCR+1)
#define VA_MASK_DCR    (VA_MAXADDR_DCR ^ VA_MINADDR_DCR)

#define VA_MINADDR_L1P PHYMAP_MINADDR_L1P
#define VA_MAXADDR_L1P PHYMAP_MAXADDR_L1P
#define VA_SIZE_L1P    (VA_MAXADDR_L1P - VA_MINADDR_L1P+1)
#define VA_MASK_L1P    (VA_MAXADDR_L1P ^ VA_MINADDR_L1P)

#define VA_MINADDR_MU PHYMAP_MINADDR_MU
#define VA_MAXADDR_MU PHYMAP_MAXADDR_MU
#define VA_SIZE_MU    (VA_MAXADDR_MU - VA_MINADDR_MU+1)
#define VA_MASK_MU    (VA_MAXADDR_MU ^ VA_MINADDR_MU)

#define VA_MINADDR_NU PHYMAP_MINADDR_NU
#define VA_MAXADDR_NU PHYMAP_MAXADDR_NU
#define VA_SIZE_NU    (VA_MAXADDR_NU - VA_MINADDR_NU+1)
#define VA_MASK_NU    (VA_MAXADDR_NU ^ VA_MINADDR_NU)

#define VA_MINADDR_L2 PHYMAP_MINADDR_L2
#define VA_MAXADDR_L2 PHYMAP_MAXADDR_L2
#define VA_SIZE_L2    (VA_MAXADDR_L2 - VA_MINADDR_L2+1)
#define VA_MASK_L2    (VA_MAXADDR_L2 ^ VA_MINADDR_L2)

#define VA_MINADDR_UPC PHYMAP_MINADDR_UPC
#define VA_MAXADDR_UPC PHYMAP_MAXADDR_UPC
#define VA_SIZE_UPC    (VA_MAXADDR_UPC - VA_MINADDR_UPC+1)
#define VA_MASK_UPC    (VA_MAXADDR_UPC ^ VA_MINADDR_UPC)

#define VA_MINADDR_INTAG PHYMAP_MINADDR_INTAG
#define VA_MAXADDR_INTAG PHYMAP_MAXADDR_INTAG
#define VA_SIZE_INTAG    (VA_MAXADDR_INTAG - VA_MINADDR_INTAG+1)
#define VA_MASK_INTAG    (VA_MAXADDR_INTAG ^ VA_MINADDR_INTAG)

#define VA_MINADDR_PCICFG PHYMAP_MINADDR_PCICFG
#define VA_MAXADDR_PCICFG PHYMAP_MAXADDR_PCICFG
#define VA_SIZE_PCICFG    (VA_MAXADDR_PCICFG - VA_MINADDR_PCICFG+1)
#define VA_MASK_PCICFG    (VA_MAXADDR_PCICFG ^ VA_MINADDR_PCICFG)

#define VA_MINADDR_FLASH PHYMAP_MINADDR_FLASH
#define VA_MAXADDR_FLASH PHYMAP_MAXADDR_FLASH
#define VA_SIZE_FLASH    (VA_MAXADDR_FLASH - VA_MINADDR_FLASH+1)
#define VA_MASK_FLASH    (VA_MAXADDR_FLASH ^ VA_MINADDR_FLASH)

#define VA_MINADDR_PCIIO PHYMAP_MINADDR_PCIIO
#define VA_MAXADDR_PCIIO PHYMAP_MAXADDR_PCIIO
#define VA_SIZE_PCIIO    (VA_MAXADDR_PCIIO - VA_MINADDR_PCIIO+1)
#define VA_MASK_PCIIO    (VA_MAXADDR_PCIIO ^ VA_MINADDR_PCIIO)

#define VA_MINADDR_BEDRAM_ATOMICOPS PHYMAP_MINADDR_BEDRAM_ATOMICOPS
#define VA_MAXADDR_BEDRAM_ATOMICOPS PHYMAP_MAXADDR_BEDRAM_ATOMICOPS
#define VA_SIZE_BEDRAM_ATOMICOPS    (VA_MAXADDR_BEDRAM_ATOMICOPS - VA_MINADDR_BEDRAM_ATOMICOPS+1)
#define VA_MASK_BEDRAM_ATOMICOPS    (VA_MAXADDR_BEDRAM_ATOMICOPS ^ VA_MINADDR_BEDRAM_ATOMICOPS)

#define VA_MINADDR_BEDRAM PHYMAP_MINADDR_BEDRAM
#define VA_MAXADDR_BEDRAM PHYMAP_MAXADDR_BEDRAM
#define VA_SIZE_BEDRAM   (VA_MAXADDR_BEDRAM - VA_MINADDR_BEDRAM+1)
#define VA_MASK_BEDRAM   (VA_MAXADDR_BEDRAM ^ VA_MINADDR_BEDRAM)

#define VA_PRIVILEGEDOFFSET PHYMAP_PRIVILEGEDOFFSET

#endif // Add nothing below this line.
